### PR TITLE
Rewrite for Good version 6

### PR DESCRIPTION
**Pull request by arb**
@fhemberger - This should be more than enough to get you going in the right direction. I would add more tests just to verify it works as expected, but it seems like it does from my testing.

I would also suggest following proper semver and making this version 1. You may also want to go through and do some style cleanup as well; the hapi style dies hard once you get used to it :sweat_smile:

### CODE REVIEW

**Comment by fhemberger** [comment]
Wow, thanks! Yes, this update was planned as v1.0.0 release.

**Comment by arb** [comment]
@fhemberger removed API values in test. Also added `peerDependency`.

**Comment by fhemberger** [comment]
Again, thank you so much for helping me with this! :+1:

**Comment by arb** [comment]
You're welcome :cake:.

**Pull request merged**
